services:
  - type: web
    name: citesched-server
    runtime: docker
    rootDir: .
    dockerfilePath: citesched_server/Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /startupz
    envVars:
      - key: SERVERPOD_DATABASE_PASSWORD
        sync: false
      - key: SERVERPOD_SERVICE_SECRET
        sync: false
      - key: SERVERPOD_EMAIL_SECRET_HASH_PEPPER
        sync: false
      - key: SERVERPOD_JWT_HMAC_SHA512_PRIVATE_KEY
        sync: false
      - key: SERVERPOD_JWT_REFRESH_TOKEN_HASH_PEPPER
        sync: false
      - key: SERVERPOD_SERVER_SIDE_SESSION_KEY_HASH_PEPPER
        sync: false
      - key: SERVERPOD_SHARED_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        sync: false
      - key: SMTP_SSL
        sync: false
      - key: SMTP_IGNORE_BAD_CERT
        sync: false
      - key: SERVERPOD_GOOGLE_CLIENT_SECRET_JSON
        sync: false
      - key: GEMINI_API_KEY
        sync: false
