name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd citesched_flutter && flutter pub get
          cd ../citesched_server && dart pub get

      - name: Generate Reports
        run: |
          # Generate analysis report for SonarCloud
          rm -f analysis_report.txt
          rm -rf citesched_flutter/coverage citesched_server/coverage

          pushd citesched_flutter
          flutter analyze --write=../analysis_report.txt || true
          # Generate coverage file for Flutter
          flutter test --coverage
          popd

          # Generate coverage file for Server (unit tests only)
          pushd citesched_server
          dart test test/unit -r expanded --chain-stack-traces --coverage=coverage
          dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
          popd

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}